repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: check-added-large-files
          args: [--maxkb, "100000"]
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-json
        - id: check-ast
        - id: pretty-format-json
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args:
        - --fix
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
