repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: check-added-large-files
          args: [--maxkb, "100000"]
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-json
        - id: check-ast
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
        - id: black-jupyter
